version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: projeto-vetel:latest
    restart: unless-stopped
    
    # Environment variables for Coolify
    environment:
      # Database Configuration (External MySQL) - REQUIRED
      - DB_HOST=${DB_HOST:?}
      - DB_PORT=${DB_PORT:?3306}
      - DB_DATABASE=${DB_DATABASE:?formulario_bd}
      - DB_USERNAME=${DB_USERNAME:?}
      - DB_PASSWORD=${DB_PASSWORD:?}
      - DB_CHARSET=utf8
      
      # Application Settings
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      
      # Timezone
      - TIMEZONE=${TIMEZONE:-America/Sao_Paulo}
      
      # Session Configuration
      - SESSION_LIFETIME=${SESSION_LIFETIME:-120}
      - SESSION_SECURE_COOKIE=${SESSION_SECURE_COOKIE:-true}
      - SESSION_HTTP_ONLY=${SESSION_HTTP_ONLY:-true}
      
      # Photo Storage Configuration
      - PHOTO_STORAGE_PATH=/var/www/html/img/album
      
      # Coolify FQDN - will be set automatically
      - SERVICE_FQDN_APP_80=https://rdo.vetel.ind.br
    
    # Volume configuration with named volumes
    volumes:
      # Persistent storage using named volumes
      - uploads:/var/www/html/img/album
      - reports:/var/www/html/relatorios
      - sessions:/var/www/sessions
      - logs:/var/log/apache2
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Port mapping (Coolify handles this automatically)
    ports:
      - "80:80"
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 256M

# Named volumes with local driver
volumes:
  uploads:
    driver: local
  reports:
    driver: local
  sessions:
    driver: local
  logs:
    driver: local