version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: projeto-vetel:latest
    restart: unless-stopped
    
    # Environment variables for Coolify
    environment:
      # Database Configuration (External MySQL) - REQUIRED
      - DB_HOST=${DB_HOST:?}
      - DB_PORT=${DB_PORT:?3306}
      - DB_NAME=${DB_NAME:?formulario_bd}
      - DB_USERNAME=${DB_USERNAME:?}
      - DB_PASSWORD=${DB_PASSWORD:?}
      
      # Application Settings
      - APP_ENV=${APP_ENV:?production}
      - APP_DEBUG=${APP_DEBUG:?false}
      - APP_URL=https://rdo.vetel.ind.br
      
      # Timezone
      - TIMEZONE=${TIMEZONE:?America/Sao_Paulo}
      
      # Session Configuration
      - SESSION_LIFETIME=${SESSION_LIFETIME:?3600}
      - SESSION_SECURE_COOKIE=${SESSION_SECURE_COOKIE:?true}
      
      # Admin Credentials - Use Coolify's magic variables
      - ADMIN_USERNAME=${ADMIN_USERNAME:?admin}
      - ADMIN_PASSWORD=${SERVICE_PASSWORD_ADMIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL:?admin@vetel.ind.br}
      
      # File Upload Settings
      - PHOTO_STORAGE_PATH=/var/www/html/img/album
      - MAX_UPLOAD_SIZE=10M
      - UPLOAD_MAX_FILESIZE=10M
      - POST_MAX_SIZE=100M
      
      # Security Keys - Auto-generated by Coolify
      - JWT_SECRET=${SERVICE_PASSWORD_64_JWT}
      - APP_KEY=${SERVICE_PASSWORD_64_APPKEY}
      
      # Email Configuration (Optional)
      - MAIL_DRIVER=${MAIL_DRIVER:-smtp}
      - MAIL_HOST=${MAIL_HOST:-}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION:-tls}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-noreply@vetel.ind.br}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME:-RDO Vetel}
      
      # Coolify FQDN - will be set automatically
      - SERVICE_FQDN_APP_80=https://rdo.vetel.ind.br
    
    # Volume configuration with named volumes
    volumes:
      # Persistent storage using named volumes
      - uploads:/var/www/html/img/album
      - reports:/var/www/html/relatorios
      - sessions:/var/www/sessions
      - logs:/var/log/apache2
      
      # Create .env file dynamically
      - type: bind
        source: ./.env
        target: /var/www/html/.env
        is_directory: false
        content: |
          # Auto-generated .env file
          DB_HOST=${DB_HOST}
          DB_PORT=${DB_PORT}
          DB_NAME=${DB_NAME}
          DB_USERNAME=${DB_USERNAME}
          DB_PASSWORD=${DB_PASSWORD}
          APP_ENV=${APP_ENV}
          APP_DEBUG=${APP_DEBUG}
          APP_URL=https://rdo.vetel.ind.br
          TIMEZONE=${TIMEZONE}
          SESSION_LIFETIME=${SESSION_LIFETIME}
          SESSION_SECURE_COOKIE=${SESSION_SECURE_COOKIE}
          ADMIN_USERNAME=${ADMIN_USERNAME}
          ADMIN_PASSWORD=${ADMIN_PASSWORD}
          ADMIN_EMAIL=${ADMIN_EMAIL}
          PHOTO_STORAGE_PATH=${PHOTO_STORAGE_PATH}
          MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE}
          JWT_SECRET=${JWT_SECRET}
          APP_KEY=${APP_KEY}
          MAIL_DRIVER=${MAIL_DRIVER}
          MAIL_HOST=${MAIL_HOST}
          MAIL_PORT=${MAIL_PORT}
          MAIL_USERNAME=${MAIL_USERNAME}
          MAIL_PASSWORD=${MAIL_PASSWORD}
          MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
          MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
          MAIL_FROM_NAME=${MAIL_FROM_NAME}
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Port mapping (Coolify handles this automatically)
    ports:
      - "80:80"
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 256M

# Named volumes with local driver
volumes:
  uploads:
    driver: local
  reports:
    driver: local
  sessions:
    driver: local
  logs:
    driver: local