version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    environment:
      # Database Configuration (External MySQL)
      # Using both DB_NAME and DB_DATABASE for compatibility
      DB_HOST: "103.199.185.165"
      DB_PORT: "5987"
      DB_NAME: "default"
      DB_DATABASE: "default"
      DB_USERNAME: "mariadb"
      DB_PASSWORD: "hr6nhoC6TWfMyAoFZbhB4TPsKoomu00U0gGov1MIsiTihJiG4KTBYXJrpzW2g1n8"
      DB_CHARSET: "utf8"

      # Application Settings
      APP_ENV: "production"
      APP_DEBUG: "false"

      # Timezone
      TIMEZONE: "America/Sao_Paulo"

      # Session Configuration
      SESSION_LIFETIME: "120"
      SESSION_SECURE_COOKIE: "false"
      SESSION_HTTP_ONLY: "true"

      # Photo Storage Configuration
      PHOTO_STORAGE_PATH: "/var/www/html/img/album"

    volumes:
      # Using bind mounts for Coolify
      - ./uploads:/var/www/html/img/album
      - ./reports:/var/www/html/relatorios
      - ./sessions:/var/www/sessions
      - ./logs:/var/log/apache2

    # Health check for monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health-simple.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Expose port 80 for Coolify proxy
    expose:
      - 80

    # Labels for Coolify (optional but recommended)
    labels:
      - "coolify.managed=true"
      - "coolify.type=application"
      - "coolify.name=projeto-vetel-rdo"