version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    environment:
      # Database Configuration (External MySQL)
      DB_HOST: "103.199.185.165"
      DB_PORT: "5987"
      DB_DATABASE: "default"
      DB_USERNAME: "mariadb"
      DB_PASSWORD: "hr6nhoC6TWfMyAoFZbhB4TPsKoomu00U0gGov1MIsiTihJiG4KTBYXJrpzW2g1n8"
      DB_CHARSET: "utf8"

      # Application Settings
      APP_ENV: "production"
      APP_DEBUG: "false"

      # Timezone
      TIMEZONE: "America/Sao_Paulo"

      # Session Configuration
      SESSION_LIFETIME: "120"
      SESSION_SECURE_COOKIE: "false"
      SESSION_HTTP_ONLY: "true"

      # Photo Storage Configuration
      PHOTO_STORAGE_PATH: "/var/www/html/img/album"

    volumes:
      - ./uploads:/var/www/html/img/album
      - ./reports:/var/www/html/relatorios
      - ./sessions:/var/www/sessions
      - ./logs:/var/log/apache2

    # Expose port 80 for Coolify
    expose:
      - 80